### ISSUE TITLE
[Bug] Docs check errors

### ISSUE THREAD

**Issue by XianyuanLiu** [pykale/pykale#274]
# 🐛 Bug

Docs check in PR #273 and #272 failed may due to something upgraded. It was fine before today. Docs check in #272 was passed successfully 2 days ago but failed today. It may be raised by something upgraded.

## To reproduce

https://readthedocs.org/projects/pykale/builds/15509110/

** Stack trace/error message **

```
Running Sphinx v4.3.1
loading translations [en]... done
making output directory... done
WARNING: html_static_path entry '_static' does not exist
[autosummary] generating autosummary for: index.rst, installation.md, introduction.md, kale.embed.rst, kale.evaluate.rst, kale.interpret.rst, kale.loaddata.rst, kale.pipeline.rst, kale.predict.rst, kale.prepdata.rst, kale.utils.rst, notebooks.md, tutorial.md, yaml.md
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 14 source files that are out of date
updating environment: [new config] 14 added, 0 changed, 0 removed
reading sources... [  7%] index
reading sources... [ 14%] installation
reading sources... [ 21%] introduction
reading sources... [ 28%] kale.embed
reading sources... [ 35%] kale.evaluate
reading sources... [ 42%] kale.interpret
reading sources... [ 50%] kale.loaddata
reading sources... [ 57%] kale.pipeline
reading sources... [ 64%] kale.predict
reading sources... [ 71%] kale.prepdata
reading sources... [ 78%] kale.utils
reading sources... [ 85%] notebooks
reading sources... [ 92%] tutorial
reading sources... [100%] yaml

/home/docs/checkouts/readthedocs.org/user_builds/pykale/envs/273/lib/python3.7/site-packages/recommonmark/parser.py:65: UserWarning: Container node skipped: type=document
  warn("Container node skipped: type={0}".format(mdnode.t))
/home/docs/checkouts/readthedocs.org/user_builds/pykale/envs/273/lib/python3.7/site-packages/recommonmark/parser.py:65: UserWarning: Container node skipped: type=document
  warn("Container node skipped: type={0}".format(mdnode.t))
/home/docs/checkouts/readthedocs.org/user_builds/pykale/checkouts/273/kale/embed/image_cnn.py:docstring of kale.embed.image_cnn:3: WARNING: Unexpected indentation.
/home/docs/checkouts/readthedocs.org/user_builds/pykale/checkouts/273/kale/embed/mpca.py:docstring of kale.embed.mpca.MPCA.fit:6: WARNING: Definition list ends without a blank line; unexpected unindent.
/home/docs/checkouts/readthedocs.org/user_builds/pykale/checkouts/273/kale/embed/video_feature_extractor.py:docstring of kale.embed.video_feature_extractor.get_video_feat_extractor:17: WARNING: Unexpected indentation.
/home/docs/checkouts/readthedocs.org/user_builds/pykale/checkouts/273/kale/embed/video_feature_extractor.py:docstring of kale.embed.video_feature_extractor.get_video_feat_extractor:18: WARNING: Block quote ends without a blank line; unexpected unindent.
/home/docs/checkouts/readthedocs.org/user_builds/pykale/checkouts/273/kale/embed/video_i3d.py:docstring of kale.embed.video_i3d.InceptionI3d:3: WARNING: Unexpected indentation.
/home/docs/checkouts/readthedocs.org/user_builds/pykale/checkouts/273/kale/embed/video_i3d.py:docstring of kale.embed.video_i3d.InceptionI3d:6: WARNING: Block quote ends without a blank line; unexpected unindent.
/home/docs/checkouts/readthedocs.org/user_builds/pykale/checkouts/273/kale/embed/video_se_i3d.py:docstring of kale.embed.video_se_i3d.SEInceptionI3DRGB:7: WARNING: Unexpected indentation.
/home/docs/checkouts/readthedocs.org/user_builds/pykale/checkouts/273/kale/embed/video_se_i3d.py:docstring of kale.embed.video_se_i3d.SEInceptionI3DRGB:8: WARNING: Block quote ends without a blank line; unexpected unindent.
/home/docs/checkouts/readthedocs.org/user_builds/pykale/checkouts/273/kale/loaddata/multi_domain.py:docstring of kale.loaddata.multi_domain.make_multi_domain_set:9: WARNING: Unexpected indentation.
/home/docs/checkouts/readthedocs.org/user_builds/pykale/checkouts/273/kale/loaddata/multi_domain.py:docstring of kale.loaddata.multi_domain.make_multi_domain_set:10: WARNING: Block quote ends without a blank line; unexpected unindent.
/home/docs/checkouts/readthedocs.org/user_builds/pykale/checkouts/273/docs/source/kale.pipeline.rst:34: WARNING: Title underline too short.

kale.pipeline.multi\_domain\_adapter module
------------------------------------
/home/docs/checkouts/readthedocs.org/user_builds/pykale/checkouts/273/docs/source/kale.pipeline.rst:34: WARNING: Title underline too short.

kale.pipeline.multi\_domain\_adapter module
------------------------------------
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [  7%] index
writing output... [ 14%] installation
writing output... [ 21%] introduction
writing output... [ 28%] kale.embed
writing output... [ 35%] kale.evaluate
writing output... [ 42%] kale.interpret
writing output... [ 50%] kale.loaddata
writing output... [ 57%] kale.pipeline
writing output... [ 64%] kale.predict
writing output... [ 71%] kale.prepdata
writing output... [ 78%] kale.utils
writing output... [ 85%] notebooks
writing output... [ 92%] tutorial
writing output... [100%] yaml

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/pykale/envs/273/lib/python3.7/site-packages/sphinx/cmd/build.py", line 280, in build_main
    app.build(args.force_all, filenames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pykale/envs/273/lib/python3.7/site-packages/sphinx/application.py", line 344, in build
    self.builder.build_update()
  File "/home/docs/checkouts/readthedocs.org/user_builds/pykale/envs/273/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 296, in build_update
    len(to_build))
  File "/home/docs/checkouts/readthedocs.org/user_builds/pykale/envs/273/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 358, in build
    self.write(docnames, list(updated_docnames), method)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pykale/envs/273/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 532, in write
    self._write_serial(sorted(docnames))
  File "/home/docs/checkouts/readthedocs.org/user_builds/pykale/envs/273/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 542, in _write_serial
    self.write_doc(docname, doctree)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pykale/envs/273/lib/python3.7/site-packages/sphinx/builders/html/__init__.py", line 626, in write_doc
    self.docwriter.write(doctree, destination)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pykale/envs/273/lib/python3.7/site-packages/docutils/writers/__init__.py", line 78, in write
    self.translate()
  File "/home/docs/checkouts/readthedocs.org/user_builds/pykale/envs/273/lib/python3.7/site-packages/sphinx/writers/html.py", line 71, in translate
    self.document.walkabout(visitor)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pykale/envs/273/lib/python3.7/site-packages/docutils/nodes.py", line 227, in walkabout
    if child.walkabout(visitor):
  File "/home/docs/checkouts/readthedocs.org/user_builds/pykale/envs/273/lib/python3.7/site-packages/docutils/nodes.py", line 227, in walkabout
    if child.walkabout(visitor):
  File "/home/docs/checkouts/readthedocs.org/user_builds/pykale/envs/273/lib/python3.7/site-packages/docutils/nodes.py", line 227, in walkabout
    if child.walkabout(visitor):
  File "/home/docs/checkouts/readthedocs.org/user_builds/pykale/envs/273/lib/python3.7/site-packages/docutils/nodes.py", line 219, in walkabout
    visitor.dispatch_visit(self)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pykale/envs/273/lib/python3.7/site-packages/sphinx/util/docutils.py", line 477, in dispatch_visit
    method(node)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pykale/envs/273/lib/python3.7/site-packages/sphinx/writers/html5.py", line 424, in visit_literal_block
    location=node, **highlight_args
  File "/home/docs/checkouts/readthedocs.org/user_builds/pykale/envs/273/lib/python3.7/site-packages/sphinx/highlighting.py", line 149, in highlight_block
    lexer = self.get_lexer(source, lang, opts, force, location)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pykale/envs/273/lib/python3.7/site-packages/sphinx/highlighting.py", line 133, in get_lexer
    lexer = get_lexer_by_name(lang, **opts)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pykale/envs/273/lib/python3.7/site-packages/pygments/lexers/__init__.py", line 115, in get_lexer_by_name
    for cls in find_plugin_lexers():
  File "/home/docs/checkouts/readthedocs.org/user_builds/pykale/envs/273/lib/python3.7/site-packages/pygments/plugin.py", line 54, in find_plugin_lexers
    yield entrypoint.load()
  File "/home/docs/checkouts/readthedocs.org/user_builds/pykale/envs/273/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2450, in load
    return self.resolve()
  File "/home/docs/checkouts/readthedocs.org/user_builds/pykale/envs/273/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2456, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pykale/envs/273/lib/python3.7/site-packages/ipython-8.0.0a1-py3.7.egg/IPython/__init__.py", line 43, in <module>
    """)
ImportError: 
IPython 8+ supports Python 3.8 and above, following NEP 29.
When using Python 2.7, please install IPython 5.x LTS Long Term Support version.
Python 3.3 and 3.4 were supported up to IPython 6.x.
Python 3.5 was supported with IPython 7.0 to 7.9.
Python 3.6 was supported with IPython up to 7.16.
Python 3.7 was still supported with the 7.x branch.

See IPython `README.rst` file for more information:

    https://github.com/ipython/ipython/blob/master/README.rst



Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/pykale/envs/273/lib/python3.7/site-packages/ipython-8.0.0a1-py3.7.egg/IPython/__init__.py", line 43, in <module>
    """)
ImportError: 
IPython 8+ supports Python 3.8 and above, following NEP 29.
When using Python 2.7, please install IPython 5.x LTS Long Term Support version.
Python 3.3 and 3.4 were supported up to IPython 6.x.
Python 3.5 was supported with IPython 7.0 to 7.9.
Python 3.6 was supported with IPython up to 7.16.
Python 3.7 was still supported with the 7.x branch.

See IPython `README.rst` file for more information:

    https://github.com/ipython/ipython/blob/master/README.rst
The full traceback has been saved in /tmp/sphinx-err-a21jm5z1.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

## Expected Behaviour

Test is successful.

**Comment by sz144** [comment]
The problem seems brought by the IPython version. Shall we fix the version to 7.x @haipinglu @bobturneruk ?

**Comment by bobturneruk** [comment]
If this is limited in scope to building the docs (i.e. not needed for normal pykale use), yes pin it at whatever modern version works.
